# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardmaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('productname', models.CharField(default='', max_length=100, unique=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=100)),
                ('premium', models.BooleanField(default=False)),
                ('user_upload', models.BooleanField(default=False)),
                ('layout', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardmaker.users'),
        ),
    ]
